catalogueapp/urls.py
from django.urls import path, include

app_name = 'catelogueapp'


from . import views
urlpatterns = [
    path('', views.category_view, name="category"),
    path('product/<slug>', views.product_view, name="product"),
    path('add/category', views.addCategory_view, name="addCategory"),
    path('add/product/<slug>', views.addProduct_view, name="addProduct"),
    path('edit/product/<id>', views.edit_product_view, name="editProduct"),
    path('edit/category/<id>', views.edit_catelogue_view, name="editCategory"),
    path('purchase/<id>', views.purchase_view, name="makePurchase"),
]

main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'


urlpatterns = [
    path('', views.home_view, name="home"),
]

tyreproject/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from accounts import views as acctViews
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view),
    path('catelogue/', include('catalogueapp.urls')),

    path('login/', acctViews.login_view, name="login"),
    path('logout/', acctViews.logout_view, name="logout"),

]
# For static urls  
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogueapp/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
import random

def upload_location(instance, filename):
	file_path = 'oslounitedcompany/{image}'.format(image=filename)
	return file_path


# Create your models here.
class Catelogues(models.Model):
	title        = models.CharField(max_length=100)
	slug         = models.SlugField(unique=True, blank=True)
	body         = models.TextField()
	date         = models.DateTimeField(auto_now_add=True)
	thumb        = models.ImageField(blank=True, upload_to=upload_location)
	# author       = models.ForeignKey(User, default=None,  on_delete=models.CASCADE)
	
	def __str__(self):
		return self.title
			
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title+str(random.randint(0,22)))

pre_save.connect(pre_save_blog_post_receiver, sender=Catelogues)




# Create your models here.
class Products(models.Model):
	title        = models.CharField(max_length=100)
	price        = models.PositiveIntegerField(blank=True)
	body         = models.TextField()
	date         = models.DateTimeField(auto_now_add=True)
	catelogue 	 = models.ForeignKey(Catelogues, default=None, on_delete=models.CASCADE)
	thumb        = models.ImageField(blank=True, upload_to=upload_location)
	# author       = models.ForeignKey(User, default=None,  on_delete=models.CASCADE)

	def __str__(self):
		return self.title
			

catalogueapp/forms.py
from django import forms

from .models import Catelogues, Products 


class CreateCatelogueForm(forms.ModelForm):

	class Meta:
		model = Catelogues
		fields = ['title', 'body', 'thumb']


class CreateProductForm(forms.ModelForm):

	class Meta:
		model = Products
		fields = ['title', 'price', 'thumb']



class UpdateCatelogueForm(forms.ModelForm):

	class Meta:
		model = Catelogues
		fields = ['title', 'body', 'thumb']

	def save(self, commit=True):
		catelogue = self.instance
		catelogue.title = self.cleaned_data['title']
		catelogue.price = self.cleaned_data['body']

		if self.cleaned_data['thumb']:
			catelogue.thumb = self.cleaned_data['thumb']

		if commit:
			catelogue.save()
		return catelogue

class UpdateProductForm(forms.ModelForm):

	class Meta:
		model = Products
		fields = ['title', 'price', 'thumb']

	def save(self, commit=True):
		product = self.instance
		product.title = self.cleaned_data['title']
		product.price = self.cleaned_data['price']

		if self.cleaned_data['thumb']:
			product.thumb = self.cleaned_data['thumb']

		if commit:
			product.save()
		return product

catalogueapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from .forms import CreateCatelogueForm, CreateProductForm, UpdateCatelogueForm, UpdateProductForm
from django.shortcuts import render
from operator import attrgetter



from .models import Catelogues, Products
from django.db.models import Q

from decouple import config



# catelogue_PER_PAGE = 1


# Create your views here.

# List of all categories 
def category_view(request):
	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	catelogue = sorted(get_blog_queryset(query), key=attrgetter('date'), reverse=True)
	context['catelogue'] = catelogue

	return render(request, "catalogueapp/category.html", context)


def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = Catelogues.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

# Add category view 
def addCategory_view(request):
	context = {}
	user = request.user
	if not user.is_authenticated:
		return redirect('/')

	form = CreateCatelogueForm(request.POST or None, request.FILES or None)
	if request.method == 'POST':     
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			form = CreateCatelogueForm()
			return redirect("/catelogue")
		else:
			context['error'] = "Error submitting form"
		
	context['form'] = form
	return render(request, "catalogueapp/addcategory.html", context)




# Inside a category_view
def product_view(request, slug):
	context = {}
	catelogue = Catelogues.objects.filter(slug=slug).first()

	product = Products.objects.filter(catelogue=catelogue)

	context['product'] = product
	context['catelogue'] = catelogue
	phoneNumber = config('PhoneNumber')
	context['link'] =  request.scheme+'://'+request.META['HTTP_HOST']+"/catelogue/purchase/"
	context['whatsapp']= "https://api.whatsapp.com/send/?phone=%2B"+phoneNumber+"&text=Hi,+I+want+to+purchase+this+product+"


	return render(request, "catalogueapp/product.html", context)


def purchase_view(request, id):
	context = {}
	product = Products.objects.filter(id=id).first()
	context['product'] = product

	return render(request, "catalogueapp/purchase.html", context)



# Add Product to category 
def addProduct_view(request, slug):
	context = {}
	user = request.user
	if not user.is_authenticated:
		return redirect('/')

	form = CreateProductForm(request.POST or None, request.FILES or None)
	catelogue = get_object_or_404(Catelogues, slug=slug)

	if request.method == 'POST':     
		if form.is_valid():
			obj = form.save(commit=False)
			obj.catelogue = catelogue
			obj.save()
			form = CreateProductForm()
			return redirect("/catelogue/product/"+slug)
		else:
			context['error'] = "Error submitting form"
		
	context['form'] = form
	context['catelogue'] = catelogue
	return render(request, "catalogueapp/addProduct.html", context)


def edit_product_view(request, id):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("/")

	product = get_object_or_404(Products, id=id)


	if request.POST:
		if request.POST.get("delete"):
			product.delete()
			return redirect("/catelogue/")

			

		form = UpdateProductForm(request.POST or None, request.FILES or None, instance=product)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			product = obj

	form = UpdateProductForm(
			initial = {
					"title": product.title,
					"price": product.price,
					"thumb": product.thumb,
			}
		)

	context['form'] = form
	return render(request, 'catalogueapp/editProduct.html', context)





def edit_catelogue_view(request, id):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("/")

	catelogue = get_object_or_404(Catelogues, slug=id)


	if request.POST:
		if request.POST.get("delete"):
			catelogue.delete()
			return redirect("/catelogue/")

			

		form = UpdateCatelogueForm(request.POST or None, request.FILES or None, instance=catelogue)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			catelogue = obj

	form = UpdateCatelogueForm(
			initial = {
					"title": catelogue.title,
					"body": catelogue.body,
					"thumb": catelogue.thumb,
			}
		)

	context['form'] = form
	return render(request, 'catalogueapp/editCategory.html', context)

catalogueapp/templates/catalogueapp/addProduct.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>
<div class="container" style="margin-top: 100px;">
	<div class="row">
		<div class="">
			<h1>Add a new product to <span class="text-primary">{{catelogue.title}}</span></h1>
			<p>Logged in as <b>{{request.user.username}}</b></p>
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group mt-2 mb-4">
					<label for="id_title" class="mb-2"><b>Product name</b></label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group mt-4 mb-4">
					<label for="id_body" class="mb-2"><b>Price (&#8358;)</b></label>
                    <input class="form-control" type="number" name="price" id="id_price" placeholder="Price" required autofocus>
				</div>

				<!-- Image -->
				<div class="form-group mt-4 mb-4">
					<label for="id_image"  class="mb-2"><b>Image</b></label><br>
					<input  type="file" name="thumb" id="id_image" accept="image/*" required>
				</div>
				<div class="text-danger mt-2">{{ error }}</div>	
				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>


<div style="margin-top: 100px;"></div>

{% endblock content %}

catalogueapp/templates/catalogueapp/addcategory.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>
<div class="container" style="margin-top: 100px;">
	<div class="row">
		<div class="">
			<h1>Add a new category</h1>
			<p>Logged in as <b>{{request.user.username}}</b></p>
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group mt-2 mb-4">
					<label for="id_title" class="mb-2"><b>Category Title</b></label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group mt-4 mb-4">
					<label for="id_body" class="mb-2"><b>Description</b></label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group mt-4 mb-4">
					<label for="id_image"  class="mb-2"><b>Image</b></label><br>
					<input  type="file" name="thumb" id="id_image" accept="image/*" required>
				</div>
				<div class="text-danger mt-2">{{ error }}</div>	
				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>




{% endblock content %}

catalogueapp/templates/catalogueapp/category.html
{% extends 'base.html' %}

{% load static from static %}
{% block content %}


<link href="{% static 'heroes.css' %}" rel="stylesheet">
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Oslo United Company</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              {% if request.user.is_authenticated %}
                  <a class="nav-link active" aria="page" href="/catelogue/add/category">Add category</a>
              {% else %}
              <a class="nav-link active" aria="page" href="/"> Back to Home!</a>
              {% endif %}
  
            </li>
            
          </ul>
          
          <form class="d-flex">
            {% if request.user.is_authenticated %}
                <span class="m-auto" style="color:#ffffff;">Hello, {{request.user.username}}</span> 
            <a class="nav-link active" aria="page" href="/logout"> Logout</a>

            {% else %}
                <a class="nav-link active" aria="page" href="/login"> Login</a>
            {% endif %}

            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>
  

<div class="b-example-divider"></div>


{% for post in catelogue %}
      <div class="container my-5">
        <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
          <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
            <h1 class="display-4 fw-bold lh-1">{{post.title}}</h1>
            <p class="lead">{{post.body}}</p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
              <a class="btn btn-lg btn-danger" href="{% url 'catelogueapp:product' post.slug %}">Shop Now!</a>
            </div>
            {% if request.user.is_authenticated %}
                <a class="btn btn-lg btn-secondary" href="{% url 'catelogueapp:editCategory' post.slug %}">Edit</a>
            {% endif %}
          </div>
          <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
              <img class="rounded-lg-3" src="{{post.thumb.url}}" alt="" width="520" height="600">
          </div>
        </div>
      </div>

      <div class="b-example-divider"></div>
{% endfor %}


<div style="margin-top: 30px;"></div>
  {% endblock%}

catalogueapp/templates/catalogueapp/editCategory.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container"  style="margin-top: 100px;">
	<div class="row">
		<div class="">
            <h1>Edit Category</h1>
			<p>Logged in as <b>{{request.user.username}}</b></p>
            

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group mt-2 mb-4">
					<label for="id_title" class="mb-2"><b>Title</b></label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group mt-4 mb-4">
					<label for="id_body" class="mb-2"><b>Description</b></label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required> {{form.initial.body}} </textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group mt-2 mb-4" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.thumb.url}}" id="id_image_display" height="225" width="100%">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="thumb" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
				<button class="submit-button btn btn-lg btn-danger btn-block" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete Category</button>

				<!-- Modal -->
				<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog">
				<div class="modal-content">
				<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete {{form.initial.title}}</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
				If you delete this Category, all items in this category will be deleted as well.
				</div>
				<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				<button class="submit-button btn btn-danger btn-block" type="submit" name="delete" value="delete">Delete</button>
				</div>
				</div>
				</div>
				</div>



			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

<div style="margin-top: 100px;"></div>

{% endblock content %}

catalogueapp/templates/catalogueapp/editProduct.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container"  style="margin-top: 100px;">
	<div class="row">
		<div class="">
            <h1>Edit product</h1>
			<p>Logged in as <b>{{request.user.username}}</b></p>
            

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group mt-2 mb-4">
					<label for="id_title" class="mb-2"><b>Title</b></label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group mt-2 mb-4">
					<label for="id_body" class="mb-2"><b>Price (&#8358;)</b></label>
					<input class="form-control" type="text" name="price" id="id_price" placeholder="Price" value="{{form.initial.price}}" required autofocus>
				</div>

				<!-- Image -->
				<div class="form-group image-group mt-2 mb-4" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.thumb.url}}" id="id_image_display" height="225" width="100%">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="thumb" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
				<button class="submit-button btn btn-lg btn-danger btn-block" type="submit" name="delete" value="delete">Delete Product</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

<div style="margin-top: 100px;"></div>

{% endblock content %}

catalogueapp/templates/catalogueapp/product.html
{% extends 'base.html' %}

{% load static from static %}
{% block content %}

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Oslo United Company</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link active" aria="page" href="{% url 'catelogueapp:category'%}"> Back to Catalogue!</a>
            </li>
            
          </ul>
          <form class="d-flex">
            {% if request.user.is_authenticated %}
                <span class="m-auto">Hello, {{request.user.username}}</span> 
            <a class="nav-link active" aria="page" href="/logout"> Logout</a>

            {% else %}
                <a class="nav-link active" aria="page" href="/login"> Login</a>
            {% endif %}

            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">{{catelogue.title}}</h1>

      {% if request.user.is_authenticated %}
          <a class="nav-link active" aria="page" href="/catelogue/add/product/{{catelogue.slug}}">Add to {{catelogue.title}}</a>
      {% else %}
          <a class="nav-link active" aria="page" href="/"> Back to Home!</a>
      {% endif %}


    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

{% if catelogue %}      
    {% for post in product %}
          <div class="col">
            <div class="card shadow-sm">
              <img class="rounded-lg-3" src="{{post.thumb.url}}" alt="" width="100%" height="225">


              <div class="card-body">
                <p class="card-text">{{post.title}}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">&#8358;{{post.price}}</button>
                    <a href="{{whatsapp}}{{link}}{{post.id}}&app_absent=0  "><button type="button" class="btn btn-sm btn-outline-secondary">Buy</button> </a>
                  </div>
                  {% if request.user.is_authenticated %}
                      <small class="text-muted"> <a href="/catelogue/edit/product/{{post.id}}">Edit </a></small>
                  {% else %}
                      <small class="text-muted">by Admin</small>
                  {% endif %}

                </div>
              </div>
            </div>
          </div>
      
    {% endfor %}
{% endif %}



    </div>
  </div>
</div>


  {% endblock%}

catalogueapp/templates/catalogueapp/purchase.html
{% extends 'base.html' %}

{% load static from static %}
{% block content %}

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Oslo United Company</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link active" aria="page" href="{% url 'catelogueapp:category'%}"> Back to Catalogue!</a>
            </li>
            
          </ul>
          <form class="d-flex">
            {% if request.user.is_authenticated %}
                <span class="m-auto">Hello, {{request.user.username}}</span> 
            <a class="nav-link active" aria="page" href="/logout"> Logout</a>

            {% else %}
                <a class="nav-link active" aria="page" href="/login"> Login</a>
            {% endif %}

            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

<main>

<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">{{catelogue.title}}</h1>

    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

          <div class="col">
            <div class="card shadow-sm">
              <img class="rounded-lg-3" src="{{product.thumb.url}}" alt="" width="100%" height="225">


              <div class="card-body">
                <p class="card-text">{{product.title}}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">&#8358;{{product.price}}</button>
                  </div>
                  {% if request.user.is_authenticated %}
                      <small class="text-muted"> <a href="/catelogue/edit/product/{{post.id}}">Edit </a></small>
                  {% else %}
                      <small class="text-muted">by Admin</small>
                  {% endif %}

                </div>
              </div>
            </div>
          </div>
      


    </div>
  </div>
</div>


  {% endblock%}